### ISSUE TITLE
anything I can try?

### ISSUE THREAD

**Issue by williaje11222** [tonyflo/facebook-download-photos#1]
/Users/bill/facebook-download-photos-main/download.py:127: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_elemOpening Google Chrome browser
/Users/bill/facebook-download-photos-main/download.py:67: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  browser = webdriver.Chrome(executable_path='./chromedriver',
/Users/bill/facebook-download-photos-main/download.py:67: DeprecationWarning: use options instead of chrome_options
  browser = webdriver.Chrome(executable_path='./chromedriver',
Going to Facebook
Logging into Facebook
/Users/bill/facebook-download-photos-main/download.py:75: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  email = browser.find_element_by_id("email")
/Users/bill/facebook-download-photos-main/download.py:76: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  password = browser.find_element_by_id("pass")
/Users/bill/facebook-download-photos-main/download.py:77: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  submit = browser.find_element_by_id("loginbutton")
Going to photos page for amberly.buchholz
Opening "of" photo album
Loading first photo
/Users/bill/facebook-download-photos-main/download.py:32: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  photos_tag = browser.find_element_by_xpath(xpath_str)
Traceback (most recent call last):
  File "/Users/bill/facebook-download-photos-main/download.py", line 188, in <module>
    go()
  File "/Users/bill/facebook-download-photos-main/download.py", line 97, in go
    first_photo = open_album(browser)
  File "/Users/bill/facebook-download-photos-main/download.py", line 36, in open_album
    photo_id = photo_search.group('pid')
AttributeError: 'NoneType' object has no attribute 'group'ent(by=By.XPATH, value=xpath) instead
  script_tag = browser.find_element_by_xpath(xpath_str)
Downloading https://scontent.fpit1-1.fna.fbcdn.net/v/t1.6435-9/165757816_3194737670752755_2915212266978775459_n.jpg?_nc_cat=104&ccb=1-7&_nc_sid=174925&_nc_ohc=IUUwT20z8y8AX8fbYEs&_nc_ht=scontent.fpit1-1.fna&oh=00_AT9cIlbnyfYQB4zhZGmdnj5fDCI5pNL0ioAJMmRI1PleAw&oe=62D06757
/Users/bill/facebook-download-photos-main/download.py:19: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  body = browser.find_element_by_xpath('/html/body')
Downloaded 1 Facebook photos

**Comment by tonyflo** [comment]
Seems like find_element_by_xpath is deprecated. I updated the code to use find_element instead. Pull the changes and let me know if that works for you.

**Comment by williaje11222** [comment]
Opening "of" photo album
Loading first photo
Traceback (most recent call last):
  File "/Users/bill/facebook-download-photos/download.py", line 188, in <module>
    go()
  File "/Users/bill/facebook-download-photos/download.py", line 97, in go
    first_photo = open_album(browser)
  File "/Users/bill/facebook-download-photos/download.py", line 36, in open_album
    photo_id = photo_search.group('pid')
AttributeError: 'NoneType' object has no attribute 'group'

I don't know if this is fixable for not. Usually it's in the "of" command. The "by" will typically work fine. It usually happens when the account has a id like "100041549353134".

**Comment by tonyflo** [comment]
Seems like it's because the user does not have any tagged photos.  Can you confirm?

**Comment by williaje11222** [comment]
That may be the case. I appreciate the help. This my be the only other error I've seen. I am friends with this one and they have photos of.

Traceback (most recent call last):
  File "/Users/hi/facebook-download-photos/download.py", line 188, in <module>
    go()
  File "/Users/hi/facebook-download-photos/download.py", line 111, in go
    download(browser, username, album, sequence)
  File "/Users/hi/facebook-download-photos/download.py", line 132, in download
    uri = html_search.group('uri').replace('\\', '')
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by tonyflo** [comment]
Please let me know if my lates commit works for you.

**Comment by tonyflo** [comment]
Any luck?

**Comment by tonyflo** [comment]
No response so closing
