### ISSUE TITLE
Photos by stops at first photo

### ISSUE THREAD

**Issue by emopinata** [tonyflo/facebook-download-photos#2]
I was able to run `of` fine, but for some reason `by` seems to be tripping the break, as it downloads the first photo and stops. I'd dig into it myself, but I've got to run and I wanted to see if you had an immediate thought. Thanks!

```
Opening "by" photo album
Loading first photo
Downloading all jay.duncan "by" photos...
Downloading https://scontent-ort2-2.xx.fbcdn.net/v/t39.30808-6/283552136_10224593346173925_619845127551853562_n.jpg?_nc_cat=109&ccb=1-7&_nc_sid=e3f864&_nc_ohc=jmuXWg0CoY4AX-8alCs&_nc_ht=scontent-ort2-2.xx&oh=00_AT81i392A0jygqDKjUxVLjb6i1zm93GE1klv18AHzlZoLw&oe=62CC3B63
Downloaded 1 Facebook photos
```

**Comment by tonyflo** [comment]
Seems like this was an issue with the popup that asks if you want to receive browser notifications from Facebook. Updated the code to dismiss the popup. Can you try the latest code and let me know if that works for you?

**Comment by emopinata** [comment]
> Seems like this was an issue with the popup that asks if you want to receive browser notifications from Facebook. Updated the code to dismiss the popup. Can you try the latest code and let me know if that works for you?

No dice. I had the same thought but I tried setting it as a chromedriver option, though that didn't work either. 

I'm spinning up a fresh debian VM to try with that.

**Comment by emopinata** [comment]
No luck with Debian or Fedora either... those fail in an entirely different way:

```[WDM] - ====== WebDriver manager ======
2022-07-09 14:52:28,525 INFO ====== WebDriver manager ======
[WDM] - Current google-chrome version is 103.0.5060
2022-07-09 14:52:28,572 INFO Current google-chrome version is 103.0.5060
[WDM] - Get LATEST chromedriver version for 103.0.5060 google-chrome
2022-07-09 14:52:28,572 INFO Get LATEST chromedriver version for 103.0.5060 google-chrome
[WDM] - There is no [linux64] chromedriver for browser 103.0.5060 in cache
2022-07-09 14:52:28,742 INFO There is no [linux64] chromedriver for browser 103.0.5060 in cache
[WDM] - About to download new driver from https://chromedriver.storage.googleapis.com/103.0.5060.53/chromedriver_linux64.zip
2022-07-09 14:52:28,742 INFO About to download new driver from https://chromedriver.storage.googleapis.com/103.0.5060.53/chromedriver_linux64.zip
[WDM] - Driver has been saved in cache [/home/jalmanso/.wdm/drivers/chromedriver/linux64/103.0.5060.53]
2022-07-09 14:52:29,201 INFO Driver has been saved in cache [/home/jalmanso/.wdm/drivers/chromedriver/linux64/103.0.5060.53]
Traceback (most recent call last):
  File "/home/jalmanso/facebook-download-photos/download.py", line 208, in <module>
    go()
  File "/home/jalmanso/facebook-download-photos/download.py", line 77, in go
    browser = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
  File "/home/jalmanso/env/fb/lib64/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/home/jalmanso/env/fb/lib64/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    super().__init__(
  File "/home/jalmanso/env/fb/lib64/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 277, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/jalmanso/env/fb/lib64/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 370, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/jalmanso/env/fb/lib64/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 435, in execute
    self.error_handler.check_response(response)
  File "/home/jalmanso/env/fb/lib64/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x5567156bcb13 <unknown>
#1 0x5567154c3688 <unknown>
#2 0x5567154e7f1f <unknown>
#3 0x5567154e35aa <unknown>
#4 0x55671551e64a <unknown>
#5 0x5567155187a3 <unknown>
#6 0x5567154ee0ea <unknown>
#7 0x5567154ef225 <unknown>
#8 0x5567157042dd <unknown>
#9 0x5567157082c7 <unknown>
#10 0x5567156ee22e <unknown>
#11 0x5567157090a8 <unknown>
#12 0x5567156e2bc0 <unknown>
#13 0x5567157256c8 <unknown>
#14 0x556715725848 <unknown>
#15 0x55671573fc0d <unknown>
#16 0x7f8b8c6d1e2d <unknown>
```

**Comment by emopinata** [comment]
Ok, I've been watching it while it runs, and when it gets to the first image in the album I still see the facebook browser notification pop-up. Currently digging through it to see if I can figure out why.

**Comment by tonyflo** [comment]
My mistake. I wasn't passing in the `options` object to the Chrome driver. Instead of dismissing the notification popup, there is an option to disable it completely. Try the latest commit and let me know if you have success. Don't know what's going on with your Debian or Fedora errors though.

**Comment by emopinata** [comment]
Yeah, I'm still learning python so I don't have a good handle on troubleshooting across platforms, but I do have a 2012 mini running Catalina, so that's what I'm testing on.

Ran the new code, I don't see the pop-up anymore, but it still dies after one photo. Tried running against my own profile just to make sure it and still happened. It's like it gets to the point it should right arrow but instead the browser closes.

**Comment by emopinata** [comment]
The reason I'm plugging away at this is because a friend passed away on Tuesday and I'm trying to collect all the photos from Facebook for his celebration of life. Being able to get the `of` photos was a huge help, and I'm seeing if I can figure out the `by` issue now.

**Comment by tonyflo** [comment]
So sorry to hear that. I really want to get this working for you.

If you look at the `next_photo()` function in the code, all it does it simulates pressing the left arrow key on the keyboard. The caller then compares the previous photo id with the next photo id. Since the program is exiting after just 1 photo for you, it seems like the simulated arrow key is not working for some reason (since the photo id never changes). I've been looking into alternate ways to cycle through the photos, but no luck so far.

**Comment by emopinata** [comment]
@tonyflo I greatly appreciate your help more than I could ever convey. I was looking at that and increased the `time.sleep` from 1 to 5, watching it run, and noticed that when it tries to find the body element the controls on the photo (previous, next, etc...) disappear before it closes the browser. But if I load up the image and just hit right arrow, it goes to the next one fine, so maybe it's something with that?

**Comment by tonyflo** [comment]
Is your url by any chance redirecting to Facebook's mobile site https://**m**.facebook.com/?

**Comment by emopinata** [comment]
No, it stays on the desktop site throughout.

**Comment by emopinata** [comment]
Well, this may have been an issue with macOS and key mapping, as it's now working once I disabled all the options to send special keys in VNC viewer. Normally this mac is headless with just power, ethernet, and a web cam, but macOS has always been picky about the presence of a keyboard. 

Thank you so much for working through this with me on a weekend, and if I can find a way to improve it further I'll submit a PR 
❤️

**Comment by tonyflo** [comment]
Oh great, so happy to hear that! Wasn't sure what direction to go next.
All the best and take care :)
